### ISSUE TITLE
Issues in Export :(

### ISSUE THREAD

**Issue by xAhmedAdel** [Tachyon-S/C3-Operator#2]
When I'm done editing and I want to export the new .c3,
See what will happen in the .c3 file 

![github](https://user-images.githubusercontent.com/56580276/196210557-54cb2df5-03f4-441f-ad2c-d79e2c4b4940.png)

**Comment by Tachyon-S** [comment]
Hi, Did you do the "Faces > Triangulate Faces" step as written in the readMe?

**Comment by Tachyon-S** [comment]
Did you do the "Faces > Triangulate Faces" step as written in the readMe?

**Comment by xAhmedAdel** [comment]
> Did you do the "Faces > Triangulate Faces" step as written in the readMe?

Thanks <3
