### ISSUE TITLE
Issues in Texture after Export

### ISSUE THREAD

**Issue by xAhmedAdel** [Tachyon-S/C3-Operator#3]
the first image from blender and There is no problem but when i export it and test texture on .c3, Look what happened?
Do I have to do something specific to solve this problem?

![image](https://user-images.githubusercontent.com/56580276/198852972-18ce0a99-1ec4-4b55-be9d-3122a1135765.png)

**Comment by Tachyon-S** [comment]
Did you bake the texture? If yes, this looks like a problem in the uv map. When you export or bake make sure you choose the appropriate uv maps.

**Comment by Tachyon-S** [comment]
A useful tip is try importing your exported model back to blender. There you can see which parts of your texture are mapped to which vertices in your mesh. Also try reflecting and rotating your texture, if I recall correctly in rare circumstances it happens that the texture gets exported inverted

**Comment by xAhmedAdel** [comment]
I upload the real .c3 file from conquer and I didn't do anything else just export it and same problem , 
I did not make any modifications just import and export
![image](https://user-images.githubusercontent.com/56580276/198856419-262eaa58-5b08-45a7-b604-9c35d115d607.png)

**Comment by xAhmedAdel** [comment]
> A useful tip is try importing your exported model back to blender. There you can see which parts of your texture are mapped to which vertices in your mesh. Also try reflecting and rotating your texture, if I recall correctly in rare circumstances it happens that the texture gets exported inverted

when i import .c3 agine on blender look ? the texture also bug
![image](https://user-images.githubusercontent.com/56580276/198856630-47bcdd22-0348-4b52-a7fa-d020800ee4a4.png)

**Comment by xAhmedAdel** [comment]
oh, now i know the problem but i don't know why this happ when i export the .c3 file the UV It becomes the opposite of m it is 
1- look ? the head in lower but on the mesh up not lower
![image](https://user-images.githubusercontent.com/56580276/198856871-34e4515d-b74c-44be-9179-ec11ff2feda5.png)

**Comment by Tachyon-S** [comment]
> oh, now i know the problem but i don't know why this happ when i export the .c3 file the UV It becomes the opposite of m it is
1- look ? the head in lower but on the mesh up not lower

Yes, this happens sometimes. I am not sure when it does exactly but it is always good to check flipping your texture if it does not work.

**Comment by xAhmedAdel** [comment]
> > oh, now i know the problem but i don't know why this happ when i export the .c3 file the UV It becomes the opposite of m it is
> > 1- look ? the head in lower but on the mesh up not lower
> 
> Yes, this happens sometimes. I am not sure when it does exactly but it is always good to check flipping your texture if it does not work.

look also when try to flip it same issus in the right real .c3 and the left after export and import
![image](https://user-images.githubusercontent.com/56580276/198857203-41f97660-2c5c-429b-b65c-92e85f46a285.png)

**Comment by xAhmedAdel** [comment]
Is there anything I should do before export ?

**Comment by Tachyon-S** [comment]
If your only problem is that the texture is flipped after export, just go to photoshop or any image editor and flip the texture image. This should work.
